import { Category, Merchant } from '../types/database';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-01-alimentos-e-bebidas',
    name: 'Alimentos e Bebidas',
    slug: 'alimentos-e-bebidas',
    description: 'Bebidas, cafés, chocolates, mantimentos e alimentos em geral.',
    icon: '🛒',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-02-automotivo',
    name: 'Automotivo',
    slug: 'automotivo',
    description: 'Acessórios automotivos, óleos, pneus, som e produtos para veículos.',
    icon: '🚗',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-03-beleza',
    name: 'Beleza',
    slug: 'beleza',
    description: 'Maquiagens, perfumes, cosméticos e cuidados estéticos.',
    icon: '💄',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-04-brinquedos-e-jogos',
    name: 'Brinquedos e Jogos',
    slug: 'brinquedos-e-jogos',
    description: 'Brinquedos infantis, jogos de tabuleiro, Legos e diversão.',
    icon: '🎲',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-05-casa',
    name: 'Casa',
    slug: 'casa',
    description: 'Cama, mesa, banho, decoração, móveis e utilidades domésticas.',
    icon: '🏠',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-06-casa-inteligente',
    name: 'Casa Inteligente',
    slug: 'casa-inteligente',
    description: 'Lâmpadas inteligentes, tomadas smart, fechaduras e automação residencial.',
    icon: '💡',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-07-cd-e-vinil',
    name: 'CD e Vinil',
    slug: 'cd-e-vinil',
    description: 'Discos de vinil, CDs de música, álbuns colecionáveis e edições especiais.',
    icon: '🎵',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-08-celulares-e-acessorios',
    name: 'Celulares e Acessórios',
    slug: 'celulares-e-acessorios',
    description: 'Smartphones iPhone, Samsung, Xiaomi, capinhas, carregadores e películas.',
    icon: '📱',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-09-computadores-e-acessorios',
    name: 'Computadores e Acessórios',
    slug: 'computadores-e-acessorios',
    description: 'Notebooks, mouses, teclados, monitores, SSDs e periféricos de informática.',
    icon: '💻',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-10-cozinha',
    name: 'Cozinha',
    slug: 'cozinha',
    description: 'Air Fryers, batedeiras, panelas, cafeteiras e eletroportáteis.',
    icon: '🍳',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-11-cuidados-pessoais-e-limpeza',
    name: 'Cuidados Pessoais e Limpeza',
    slug: 'cuidados-pessoais-e-limpeza',
    description: 'Higiene pessoal, sabão, amaciantes, desinfetantes e produtos de limpeza.',
    icon: '🧴',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-12-dispositivos-amazon',
    name: 'Dispositivos Amazon',
    slug: 'dispositivos-amazon',
    description: 'Echo Dot com Alexa, Fire TV Stick, e-Readers Kindle e linha Amazon.',
    icon: '📟',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-13-dvd-e-blu-ray',
    name: 'DVD e Blu-Ray',
    slug: 'dvd-e-blu-ray',
    description: 'Filmes, séries, edições de colecionador em DVD e Blu-Ray.',
    icon: '📀',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-14-eletronicos-e-tvs',
    name: 'Eletrônicos e TVs',
    slug: 'eletronicos-e-tvs',
    description: 'Smart TVs 4K, fones de ouvido Bluetooth, soundbars e caixas de som.',
    icon: '📺',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-15-esportes-e-aventura',
    name: 'Esportes e Aventura',
    slug: 'esportes-e-aventura',
    description: 'Artigos esportivos, bicicletas, suplementos, academia e camping.',
    icon: '⚽',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-16-ferramentas-e-construcao',
    name: 'Ferramentas e Construção',
    slug: 'ferramentas-e-construcao',
    description: 'Parafusadeiras, furadeiras, kits de ferramentas e material de reforma.',
    icon: '🛠️',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-17-instrumentos-musicais',
    name: 'Instrumentos Musicais',
    slug: 'instrumentos-musicais',
    description: 'Violões, guitarras, teclados musicais, microfones e equipamentos de áudio.',
    icon: '🎸',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-18-itens-para-bebe',
    name: 'Itens para Bebê',
    slug: 'itens-para-bebe',
    description: 'Fraldas, carrinhos de bebê, mamadeiras, chupetas e produtos infantis.',
    icon: '👶',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-19-jardim-e-piscina',
    name: 'Jardim e Piscina',
    slug: 'jardim-e-piscina',
    description: 'Lavadoras de alta pressão, mangueiras, plantas, piscinas e jardinagem.',
    icon: '🪴',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-20-livros-e-ebooks',
    name: 'Livros e eBooks',
    slug: 'livros-e-ebooks',
    description: 'Livros físicos, HQs, mangás, literatura e livros digitais para Kindle.',
    icon: '📚',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-21-moda',
    name: 'Moda',
    slug: 'moda',
    description: 'Roupas masculinas e femininas, tênis, sapatos, bolsas e acessórios.',
    icon: '👕',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-22-papelaria-e-escritorio',
    name: 'Papelaria e Escritório',
    slug: 'papelaria-e-escritorio',
    description: 'Impressoras, cadernos, canetas, envelopes e suprimentos para escritório.',
    icon: '🖨️',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-23-pet-shop',
    name: 'Pet Shop',
    slug: 'pet-shop',
    description: 'Rações para cães e gatos, petiscos, brinquedos pet e higiene animal.',
    icon: '🦴',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-24-itens-gamer',
    name: 'Itens Gamer',
    slug: 'itens-gamer',
    description: 'Consoles PlayStation 5, Xbox Series, Nintendo Switch, cadeiras e jogos.',
    icon: '🎮',
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const SEED_MERCHANTS: Merchant[] = [
  {
    id: 'm1111111-1111-1111-1111-111111111111',
    name: 'Amazon Brasil',
    slug: 'amazon',
    website_url: 'https://www.amazon.com.br/',
    logo_url: null,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm2222222-2222-2222-2222-222222222222',
    name: 'Mercado Livre',
    slug: 'mercado-livre',
    website_url: 'https://www.mercadolivre.com.br/',
    logo_url: null,
    active: true,
    created_at: new Date().toISOString(),
  },
];
